services:
  booking.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
      - ConnectionStrings__Database=Server=bookify-db;Port=5432;Database=bookify;User Id=postgres;Password=123456;
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 

  bookify-idp:
    environment:
      - Keycloak__TokenUrl=Server=bookify-db;Port=5432;Database=bookify;User Id=postgres;Password=123456;